// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetPlugins():Promise<Array<main.PluginInfo>>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function GetToken():Promise<string>;

export function IsLoggedIn():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<main.LoginResult>;

export function Logout():Promise<void>;

export function Register(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<main.LoginResult>;

export function SearchSchool(arg1:string):Promise<Array<main.SchoolResult>>;

export function SetAPIBase(arg1:string):Promise<void>;
