// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelAIGenerate():Promise<void>;

export function CheckHancom():Promise<Record<string, any>>;

export function CheckOfficeStatus():Promise<Record<string, boolean>>;

export function CheckOllama():Promise<main.OllamaStatus>;

export function ConvertExcelToPdf(arg1:string,arg2:string):Promise<main.OfficeConvertResult>;

export function ConvertHwp(arg1:string,arg2:string,arg3:string):Promise<main.HwpConvertResult>;

export function ConvertHwpToPages(arg1:string,arg2:string):Promise<main.HwpPagesResult>;

export function ConvertHwpToText(arg1:string,arg2:string):Promise<main.HwpTextResult>;

export function ConvertPdfToText(arg1:string):Promise<main.ConvertToMarkdownResult>;

export function ConvertPptToPdf(arg1:string,arg2:string):Promise<main.OfficeConvertResult>;

export function ConvertToMarkdown(arg1:string,arg2:string):Promise<main.ConvertToMarkdownResult>;

export function ConvertToPdfAndImages(arg1:string,arg2:string):Promise<main.PdfConvertResult>;

export function DeleteDocumentIndex(arg1:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string):Promise<main.DownloadFileResult>;

export function GenerateAIStream(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetAIBenchmark():Promise<main.AIBenchmark>;

export function GetFileDataURL(arg1:string):Promise<string>;

export function GetIndexedDocIDs():Promise<Array<string>>;

export function GetLocalModels():Promise<Array<string>>;

export function GetPlugins():Promise<Array<main.PluginInfo>>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function GetToken():Promise<string>;

export function IndexDocument(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function InstallOllama():Promise<main.OllamaStatus>;

export function IsLoggedIn():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<main.LoginResult>;

export function Logout():Promise<void>;

export function PullModel(arg1:string):Promise<main.PullModelResult>;

export function QuitHwp():Promise<void>;

export function Register(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:number,arg11:number):Promise<main.LoginResult>;

export function SearchKnowledge(arg1:string,arg2:number):Promise<Array<main.RAGSearchResult>>;

export function SearchSchool(arg1:string):Promise<Array<main.SchoolResult>>;

export function SelectAndUploadDoc():Promise<main.UploadFileResult>;

export function SelectAndUploadFiles():Promise<Array<main.UploadFileResult>>;

export function SetAPIBase(arg1:string):Promise<void>;

export function StartOllama():Promise<main.OllamaStatus>;

export function StopOllama():Promise<main.OllamaStatus>;

export function UploadFileFromBytes(arg1:string,arg2:string):Promise<main.UploadFileResult>;
