// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckHancom() {
  return window['go']['main']['App']['CheckHancom']();
}

export function CheckOfficeStatus() {
  return window['go']['main']['App']['CheckOfficeStatus']();
}

export function CheckOllama() {
  return window['go']['main']['App']['CheckOllama']();
}

export function ConvertExcelToPdf(arg1, arg2) {
  return window['go']['main']['App']['ConvertExcelToPdf'](arg1, arg2);
}

export function ConvertHwp(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConvertHwp'](arg1, arg2, arg3);
}

export function ConvertPptToPdf(arg1, arg2) {
  return window['go']['main']['App']['ConvertPptToPdf'](arg1, arg2);
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function GetAIBenchmark() {
  return window['go']['main']['App']['GetAIBenchmark']();
}

export function GetFileDataURL(arg1) {
  return window['go']['main']['App']['GetFileDataURL'](arg1);
}

export function GetPlugins() {
  return window['go']['main']['App']['GetPlugins']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetToken() {
  return window['go']['main']['App']['GetToken']();
}

export function InstallOllama() {
  return window['go']['main']['App']['InstallOllama']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function PullModel(arg1) {
  return window['go']['main']['App']['PullModel'](arg1);
}

export function QuitHwp() {
  return window['go']['main']['App']['QuitHwp']();
}

export function Register(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SearchSchool(arg1) {
  return window['go']['main']['App']['SearchSchool'](arg1);
}

export function SelectAndUploadDoc() {
  return window['go']['main']['App']['SelectAndUploadDoc']();
}

export function SelectAndUploadFiles() {
  return window['go']['main']['App']['SelectAndUploadFiles']();
}

export function SetAPIBase(arg1) {
  return window['go']['main']['App']['SetAPIBase'](arg1);
}

export function StartOllama() {
  return window['go']['main']['App']['StartOllama']();
}

export function UploadFileFromBytes(arg1, arg2) {
  return window['go']['main']['App']['UploadFileFromBytes'](arg1, arg2);
}
