// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelAIGenerate():Promise<void>;

export function CheckConnection():Promise<boolean>;

export function CheckHancom():Promise<Record<string, any>>;

export function CheckOfficeStatus():Promise<Record<string, boolean>>;

export function CheckOllama():Promise<main.OllamaStatus>;

export function ConvertExcelToPdf(arg1:string,arg2:string):Promise<main.OfficeConvertResult>;

export function ConvertHwp(arg1:string,arg2:string,arg3:string):Promise<main.HwpConvertResult>;

export function ConvertHwpToPages(arg1:string,arg2:string):Promise<main.HwpPagesResult>;

export function ConvertHwpToText(arg1:string,arg2:string):Promise<main.HwpTextResult>;

export function ConvertPdfToText(arg1:string):Promise<main.ConvertToMarkdownResult>;

export function ConvertPptToPdf(arg1:string,arg2:string):Promise<main.OfficeConvertResult>;

export function ConvertToMarkdown(arg1:string,arg2:string):Promise<main.ConvertToMarkdownResult>;

export function ConvertToPdfAndImages(arg1:string,arg2:string):Promise<main.PdfConvertResult>;

export function ConvertWithKordoc(arg1:string,arg2:string):Promise<main.ConvertToMarkdownResult>;

export function DeleteAILog(arg1:string):Promise<void>;

export function DeleteAttendanceRecord(arg1:string):Promise<void>;

export function DeleteCounselingRecord(arg1:string):Promise<void>;

export function DeleteCurriculumEvaluation(arg1:string):Promise<void>;

export function DeleteDocumentIndex(arg1:string):Promise<void>;

export function DeleteOpinionHistory(arg1:string):Promise<void>;

export function DeleteSendocDraft(arg1:string):Promise<void>;

export function DeleteTodoItem(arg1:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string):Promise<main.DownloadFileResult>;

export function ExtractKeywordsLocalAI(arg1:string):Promise<string>;

export function GenerateAIStream(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GenerateAISync(arg1:string,arg2:string):Promise<string>;

export function GetAIBenchmark():Promise<main.AIBenchmark>;

export function GetAILogs():Promise<Array<main.AILog>>;

export function GetCounselingRecords(arg1:string):Promise<Array<main.CounselingRecord>>;

export function GetCurriculumEvaluations():Promise<Array<main.EvalRecord>>;

export function GetFileDataURL(arg1:string):Promise<string>;

export function GetIndexedDocIDs():Promise<Array<string>>;

export function GetLocalAnnouncements():Promise<Array<main.LocalAnnouncement>>;

export function GetLocalKnowledge():Promise<Array<main.KnowledgeDoc>>;

export function GetLocalLinkers():Promise<Array<main.Bookmark>>;

export function GetLocalModels():Promise<Array<string>>;

export function GetMonthAttendanceRecords(arg1:string):Promise<Array<main.AttendanceRecord>>;

export function GetOpinionHistories(arg1:string):Promise<Array<main.OpinionRecord>>;

export function GetOpinionRecords():Promise<Array<main.OpinionRecord>>;

export function GetPlugins():Promise<Array<main.PluginInfo>>;

export function GetSchoolYearRecords(arg1:number):Promise<Array<main.AttendanceRecord>>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function GetTodos(arg1:string,arg2:string):Promise<Array<main.TodoItem>>;

export function GetToken():Promise<string>;

export function HasSendocDraft(arg1:string):Promise<boolean>;

export function IndexDocument(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function InstallOllama():Promise<main.OllamaStatus>;

export function IsLoggedIn():Promise<boolean>;

export function LoadSendocDraft(arg1:string):Promise<main.SendocDraftResult>;

export function Login(arg1:string,arg2:string):Promise<main.LoginResult>;

export function Logout():Promise<void>;

export function OpenLocalAnnouncementFile(arg1:string,arg2:string):Promise<void>;

export function OpenLocalKnowledgeFile(arg1:string,arg2:string):Promise<void>;

export function OpenPrintHTML(arg1:string):Promise<void>;

export function PullModel(arg1:string):Promise<main.PullModelResult>;

export function QuitHwp():Promise<void>;

export function Register(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:number,arg11:number):Promise<main.LoginResult>;

export function SaveAILog(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveAttendanceRecord(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveAttendanceRemarks(arg1:Array<string>,arg2:string):Promise<void>;

export function SaveCounselingRecord(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveCurriculumEvaluation(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string):Promise<void>;

export function SaveFileBytes(arg1:string,arg2:string):Promise<main.DownloadFileResult>;

export function SaveOpinionHistory(arg1:string,arg2:string):Promise<void>;

export function SaveOpinionRecord(arg1:string,arg2:string):Promise<void>;

export function SaveSendocDraft(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveTodoItem(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function SearchKnowledge(arg1:string,arg2:number):Promise<Array<main.RAGSearchResult>>;

export function SearchSchool(arg1:string):Promise<Array<main.SchoolResult>>;

export function SelectAndUploadDoc():Promise<main.UploadFileResult>;

export function SelectAndUploadFiles():Promise<Array<main.UploadFileResult>>;

export function SetAPIBase(arg1:string):Promise<void>;

export function StartOllama():Promise<main.OllamaStatus>;

export function StopOllama():Promise<main.OllamaStatus>;

export function SyncAnnouncements(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SyncKnowledge(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SyncLinkers(arg1:string):Promise<void>;

export function ToggleTodoItem(arg1:string):Promise<void>;

export function UploadFileFromBytes(arg1:string,arg2:string):Promise<main.UploadFileResult>;
