// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAIGenerate() {
  return window['go']['main']['App']['CancelAIGenerate']();
}

export function CheckHancom() {
  return window['go']['main']['App']['CheckHancom']();
}

export function CheckOfficeStatus() {
  return window['go']['main']['App']['CheckOfficeStatus']();
}

export function CheckOllama() {
  return window['go']['main']['App']['CheckOllama']();
}

export function ConvertExcelToPdf(arg1, arg2) {
  return window['go']['main']['App']['ConvertExcelToPdf'](arg1, arg2);
}

export function ConvertHwp(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConvertHwp'](arg1, arg2, arg3);
}

export function ConvertHwpToPages(arg1, arg2) {
  return window['go']['main']['App']['ConvertHwpToPages'](arg1, arg2);
}

export function ConvertHwpToText(arg1, arg2) {
  return window['go']['main']['App']['ConvertHwpToText'](arg1, arg2);
}

export function ConvertPdfToText(arg1) {
  return window['go']['main']['App']['ConvertPdfToText'](arg1);
}

export function ConvertPptToPdf(arg1, arg2) {
  return window['go']['main']['App']['ConvertPptToPdf'](arg1, arg2);
}

export function ConvertToMarkdown(arg1, arg2) {
  return window['go']['main']['App']['ConvertToMarkdown'](arg1, arg2);
}

export function ConvertToPdfAndImages(arg1, arg2) {
  return window['go']['main']['App']['ConvertToPdfAndImages'](arg1, arg2);
}

export function ConvertWithKordoc(arg1, arg2) {
  return window['go']['main']['App']['ConvertWithKordoc'](arg1, arg2);
}

export function DeleteAILog(arg1) {
  return window['go']['main']['App']['DeleteAILog'](arg1);
}

export function DeleteAttendanceRecord(arg1) {
  return window['go']['main']['App']['DeleteAttendanceRecord'](arg1);
}

export function DeleteDocumentIndex(arg1) {
  return window['go']['main']['App']['DeleteDocumentIndex'](arg1);
}

export function DeleteOpinionHistory(arg1) {
  return window['go']['main']['App']['DeleteOpinionHistory'](arg1);
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function ExtractKeywordsLocalAI(arg1) {
  return window['go']['main']['App']['ExtractKeywordsLocalAI'](arg1);
}

export function GenerateAIStream(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateAIStream'](arg1, arg2, arg3);
}

export function GenerateAISync(arg1, arg2) {
  return window['go']['main']['App']['GenerateAISync'](arg1, arg2);
}

export function GetAIBenchmark() {
  return window['go']['main']['App']['GetAIBenchmark']();
}

export function GetAILogs() {
  return window['go']['main']['App']['GetAILogs']();
}

export function GetFileDataURL(arg1) {
  return window['go']['main']['App']['GetFileDataURL'](arg1);
}

export function GetIndexedDocIDs() {
  return window['go']['main']['App']['GetIndexedDocIDs']();
}

export function GetLocalModels() {
  return window['go']['main']['App']['GetLocalModels']();
}

export function GetMonthAttendanceRecords(arg1) {
  return window['go']['main']['App']['GetMonthAttendanceRecords'](arg1);
}

export function GetOpinionHistories(arg1) {
  return window['go']['main']['App']['GetOpinionHistories'](arg1);
}

export function GetOpinionRecords() {
  return window['go']['main']['App']['GetOpinionRecords']();
}

export function GetPlugins() {
  return window['go']['main']['App']['GetPlugins']();
}

export function GetSchoolYearRecords(arg1) {
  return window['go']['main']['App']['GetSchoolYearRecords'](arg1);
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetToken() {
  return window['go']['main']['App']['GetToken']();
}

export function IndexDocument(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['IndexDocument'](arg1, arg2, arg3, arg4);
}

export function InstallOllama() {
  return window['go']['main']['App']['InstallOllama']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function PullModel(arg1) {
  return window['go']['main']['App']['PullModel'](arg1);
}

export function QuitHwp() {
  return window['go']['main']['App']['QuitHwp']();
}

export function Register(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}

export function SaveAILog(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveAILog'](arg1, arg2, arg3);
}

export function SaveAttendanceRecord(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveAttendanceRecord'](arg1, arg2, arg3);
}

export function SaveAttendanceRemarks(arg1, arg2) {
  return window['go']['main']['App']['SaveAttendanceRemarks'](arg1, arg2);
}

export function SaveOpinionHistory(arg1, arg2) {
  return window['go']['main']['App']['SaveOpinionHistory'](arg1, arg2);
}

export function SaveOpinionRecord(arg1, arg2) {
  return window['go']['main']['App']['SaveOpinionRecord'](arg1, arg2);
}

export function SearchKnowledge(arg1, arg2) {
  return window['go']['main']['App']['SearchKnowledge'](arg1, arg2);
}

export function SearchSchool(arg1) {
  return window['go']['main']['App']['SearchSchool'](arg1);
}

export function SelectAndUploadDoc() {
  return window['go']['main']['App']['SelectAndUploadDoc']();
}

export function SelectAndUploadFiles() {
  return window['go']['main']['App']['SelectAndUploadFiles']();
}

export function SetAPIBase(arg1) {
  return window['go']['main']['App']['SetAPIBase'](arg1);
}

export function StartOllama() {
  return window['go']['main']['App']['StartOllama']();
}

export function StopOllama() {
  return window['go']['main']['App']['StopOllama']();
}

export function UploadFileFromBytes(arg1, arg2) {
  return window['go']['main']['App']['UploadFileFromBytes'](arg1, arg2);
}
