// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAIGenerate() {
  return window['go']['main']['App']['CancelAIGenerate']();
}

export function CheckConnection() {
  return window['go']['main']['App']['CheckConnection']();
}

export function CheckExcel() {
  return window['go']['main']['App']['CheckExcel']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckHancom() {
  return window['go']['main']['App']['CheckHancom']();
}

export function CheckOfficeStatus() {
  return window['go']['main']['App']['CheckOfficeStatus']();
}

export function CheckOllama() {
  return window['go']['main']['App']['CheckOllama']();
}

export function ClearConvertedPages(arg1) {
  return window['go']['main']['App']['ClearConvertedPages'](arg1);
}

export function ClearLocalClass(arg1, arg2) {
  return window['go']['main']['App']['ClearLocalClass'](arg1, arg2);
}

export function ConvertExcelToPdf(arg1, arg2) {
  return window['go']['main']['App']['ConvertExcelToPdf'](arg1, arg2);
}

export function ConvertHwp(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConvertHwp'](arg1, arg2, arg3);
}

export function ConvertHwpToPages(arg1, arg2) {
  return window['go']['main']['App']['ConvertHwpToPages'](arg1, arg2);
}

export function ConvertHwpToText(arg1, arg2) {
  return window['go']['main']['App']['ConvertHwpToText'](arg1, arg2);
}

export function ConvertPdfToText(arg1) {
  return window['go']['main']['App']['ConvertPdfToText'](arg1);
}

export function ConvertPptToPdf(arg1, arg2) {
  return window['go']['main']['App']['ConvertPptToPdf'](arg1, arg2);
}

export function ConvertToMarkdown(arg1, arg2) {
  return window['go']['main']['App']['ConvertToMarkdown'](arg1, arg2);
}

export function ConvertToPdfAndImages(arg1, arg2) {
  return window['go']['main']['App']['ConvertToPdfAndImages'](arg1, arg2);
}

export function ConvertWithKordoc(arg1, arg2) {
  return window['go']['main']['App']['ConvertWithKordoc'](arg1, arg2);
}

export function DeleteAILog(arg1) {
  return window['go']['main']['App']['DeleteAILog'](arg1);
}

export function DeleteAttendanceRecord(arg1) {
  return window['go']['main']['App']['DeleteAttendanceRecord'](arg1);
}

export function DeleteCounselingRecord(arg1) {
  return window['go']['main']['App']['DeleteCounselingRecord'](arg1);
}

export function DeleteCurriculumEvaluation(arg1) {
  return window['go']['main']['App']['DeleteCurriculumEvaluation'](arg1);
}

export function DeleteDocumentIndex(arg1) {
  return window['go']['main']['App']['DeleteDocumentIndex'](arg1);
}

export function DeleteLocalSendocDraft(arg1) {
  return window['go']['main']['App']['DeleteLocalSendocDraft'](arg1);
}

export function DeleteLocalStudentBatch(arg1) {
  return window['go']['main']['App']['DeleteLocalStudentBatch'](arg1);
}

export function DeleteOpinionHistory(arg1) {
  return window['go']['main']['App']['DeleteOpinionHistory'](arg1);
}

export function DeleteSendocDraft(arg1) {
  return window['go']['main']['App']['DeleteSendocDraft'](arg1);
}

export function DeleteTodoItem(arg1) {
  return window['go']['main']['App']['DeleteTodoItem'](arg1);
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function ExtractKeywordsLocalAI(arg1) {
  return window['go']['main']['App']['ExtractKeywordsLocalAI'](arg1);
}

export function GenerateAIStream(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateAIStream'](arg1, arg2, arg3);
}

export function GenerateAISync(arg1, arg2) {
  return window['go']['main']['App']['GenerateAISync'](arg1, arg2);
}

export function GetAIBenchmark() {
  return window['go']['main']['App']['GetAIBenchmark']();
}

export function GetAILogs() {
  return window['go']['main']['App']['GetAILogs']();
}

export function GetAPIBase() {
  return window['go']['main']['App']['GetAPIBase']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConvertedPage(arg1, arg2) {
  return window['go']['main']['App']['GetConvertedPage'](arg1, arg2);
}

export function GetCounselingRecords(arg1) {
  return window['go']['main']['App']['GetCounselingRecords'](arg1);
}

export function GetCurriculumEvaluations() {
  return window['go']['main']['App']['GetCurriculumEvaluations']();
}

export function GetFileDataURL(arg1) {
  return window['go']['main']['App']['GetFileDataURL'](arg1);
}

export function GetIndexedDocIDs() {
  return window['go']['main']['App']['GetIndexedDocIDs']();
}

export function GetLocalAnnouncements() {
  return window['go']['main']['App']['GetLocalAnnouncements']();
}

export function GetLocalKnowledge() {
  return window['go']['main']['App']['GetLocalKnowledge']();
}

export function GetLocalLinkers() {
  return window['go']['main']['App']['GetLocalLinkers']();
}

export function GetLocalModels() {
  return window['go']['main']['App']['GetLocalModels']();
}

export function GetLocalSendocDraft(arg1) {
  return window['go']['main']['App']['GetLocalSendocDraft'](arg1);
}

export function GetLocalSendocDrafts() {
  return window['go']['main']['App']['GetLocalSendocDrafts']();
}

export function GetLocalStudents(arg1, arg2) {
  return window['go']['main']['App']['GetLocalStudents'](arg1, arg2);
}

export function GetMonthAttendanceRecords(arg1) {
  return window['go']['main']['App']['GetMonthAttendanceRecords'](arg1);
}

export function GetOpinionHistories(arg1) {
  return window['go']['main']['App']['GetOpinionHistories'](arg1);
}

export function GetOpinionRecords() {
  return window['go']['main']['App']['GetOpinionRecords']();
}

export function GetPlugins() {
  return window['go']['main']['App']['GetPlugins']();
}

export function GetQueueLength() {
  return window['go']['main']['App']['GetQueueLength']();
}

export function GetSchoolYearRecords(arg1) {
  return window['go']['main']['App']['GetSchoolYearRecords'](arg1);
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetTodos(arg1, arg2) {
  return window['go']['main']['App']['GetTodos'](arg1, arg2);
}

export function GetToken() {
  return window['go']['main']['App']['GetToken']();
}

export function HasSendocDraft(arg1) {
  return window['go']['main']['App']['HasSendocDraft'](arg1);
}

export function IndexDocument(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['IndexDocument'](arg1, arg2, arg3, arg4);
}

export function InsertLocalStudent(arg1) {
  return window['go']['main']['App']['InsertLocalStudent'](arg1);
}

export function InstallOllama() {
  return window['go']['main']['App']['InstallOllama']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function LoadSendocDraft(arg1) {
  return window['go']['main']['App']['LoadSendocDraft'](arg1);
}

export function LoadTeacherAsset(arg1, arg2) {
  return window['go']['main']['App']['LoadTeacherAsset'](arg1, arg2);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function OpenLocalAnnouncementFile(arg1, arg2) {
  return window['go']['main']['App']['OpenLocalAnnouncementFile'](arg1, arg2);
}

export function OpenLocalKnowledgeFile(arg1, arg2) {
  return window['go']['main']['App']['OpenLocalKnowledgeFile'](arg1, arg2);
}

export function OpenPrintHTML(arg1) {
  return window['go']['main']['App']['OpenPrintHTML'](arg1);
}

export function PullModel(arg1) {
  return window['go']['main']['App']['PullModel'](arg1);
}

export function QueueOfflineAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['QueueOfflineAction'](arg1, arg2, arg3);
}

export function QueueOfflineRegistration(arg1) {
  return window['go']['main']['App']['QueueOfflineRegistration'](arg1);
}

export function QuitHwp() {
  return window['go']['main']['App']['QuitHwp']();
}

export function RefineSearchQuery(arg1) {
  return window['go']['main']['App']['RefineSearchQuery'](arg1);
}

export function Register(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}

export function SaveAILog(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveAILog'](arg1, arg2, arg3);
}

export function SaveAttendanceDays(arg1, arg2) {
  return window['go']['main']['App']['SaveAttendanceDays'](arg1, arg2);
}

export function SaveAttendanceDocs(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveAttendanceDocs'](arg1, arg2, arg3);
}

export function SaveAttendanceRecord(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveAttendanceRecord'](arg1, arg2, arg3);
}

export function SaveAttendanceRemarks(arg1, arg2) {
  return window['go']['main']['App']['SaveAttendanceRemarks'](arg1, arg2);
}

export function SaveConvertedPage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveConvertedPage'](arg1, arg2, arg3);
}

export function SaveCounselingRecord(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveCounselingRecord'](arg1, arg2, arg3, arg4);
}

export function SaveCurriculumEvaluation(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveCurriculumEvaluation'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SaveFileBytes(arg1, arg2) {
  return window['go']['main']['App']['SaveFileBytes'](arg1, arg2);
}

export function SaveLocalSendocDraft(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SaveLocalSendocDraft'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SaveOpinionHistory(arg1, arg2) {
  return window['go']['main']['App']['SaveOpinionHistory'](arg1, arg2);
}

export function SaveOpinionRecord(arg1, arg2) {
  return window['go']['main']['App']['SaveOpinionRecord'](arg1, arg2);
}

export function SaveSendocDraft(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSendocDraft'](arg1, arg2, arg3);
}

export function SaveTeacherAsset(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveTeacherAsset'](arg1, arg2, arg3);
}

export function SaveTodoItem(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveTodoItem'](arg1, arg2, arg3, arg4);
}

export function SearchKnowledge(arg1, arg2) {
  return window['go']['main']['App']['SearchKnowledge'](arg1, arg2);
}

export function SearchSchool(arg1) {
  return window['go']['main']['App']['SearchSchool'](arg1);
}

export function SelectAndUploadDoc() {
  return window['go']['main']['App']['SelectAndUploadDoc']();
}

export function SelectAndUploadFiles() {
  return window['go']['main']['App']['SelectAndUploadFiles']();
}

export function SetAPIBase(arg1) {
  return window['go']['main']['App']['SetAPIBase'](arg1);
}

export function SetToken(arg1) {
  return window['go']['main']['App']['SetToken'](arg1);
}

export function StartOllama() {
  return window['go']['main']['App']['StartOllama']();
}

export function StopOllama() {
  return window['go']['main']['App']['StopOllama']();
}

export function SyncAnnouncements(arg1, arg2, arg3) {
  return window['go']['main']['App']['SyncAnnouncements'](arg1, arg2, arg3);
}

export function SyncKnowledge(arg1, arg2, arg3) {
  return window['go']['main']['App']['SyncKnowledge'](arg1, arg2, arg3);
}

export function SyncLinkers(arg1) {
  return window['go']['main']['App']['SyncLinkers'](arg1);
}

export function SyncLocalStudentsConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SyncLocalStudentsConfig'](arg1, arg2, arg3);
}

export function SyncOfflineData() {
  return window['go']['main']['App']['SyncOfflineData']();
}

export function ToggleTodoItem(arg1) {
  return window['go']['main']['App']['ToggleTodoItem'](arg1);
}

export function UpdateLocalStudent(arg1) {
  return window['go']['main']['App']['UpdateLocalStudent'](arg1);
}

export function UploadFileFromBytes(arg1, arg2) {
  return window['go']['main']['App']['UploadFileFromBytes'](arg1, arg2);
}
