// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckDependencies():Promise<main.DependencyStatus>;

export function ClearLogs():Promise<void>;

export function GetLogs():Promise<Array<string>>;

export function GetStatus():Promise<main.ServerStatus>;

export function InstallAndStartWithScoop():Promise<void>;

export function StartServer():Promise<void>;

export function StopServer():Promise<void>;
