// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDependencies() {
  return window['go']['main']['App']['CheckDependencies']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function DeleteDBKnowledgeDoc(arg1) {
  return window['go']['main']['App']['DeleteDBKnowledgeDoc'](arg1);
}

export function DeleteDBUser(arg1) {
  return window['go']['main']['App']['DeleteDBUser'](arg1);
}

export function GetDBKnowledgeDocs() {
  return window['go']['main']['App']['GetDBKnowledgeDocs']();
}

export function GetDBUsers() {
  return window['go']['main']['App']['GetDBUsers']();
}

export function GetInactiveDBUsers() {
  return window['go']['main']['App']['GetInactiveDBUsers']();
}

export function GetLocalIP() {
  return window['go']['main']['App']['GetLocalIP']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function HardDeleteDBUser(arg1) {
  return window['go']['main']['App']['HardDeleteDBUser'](arg1);
}

export function InstallAndStartWithScoop() {
  return window['go']['main']['App']['InstallAndStartWithScoop']();
}

export function ReactivateDBUser(arg1) {
  return window['go']['main']['App']['ReactivateDBUser'](arg1);
}

export function ResetDBUserPassword(arg1, arg2) {
  return window['go']['main']['App']['ResetDBUserPassword'](arg1, arg2);
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function UpdateDBUserPosition(arg1, arg2) {
  return window['go']['main']['App']['UpdateDBUserPosition'](arg1, arg2);
}

export function UpdateDBUserRole(arg1, arg2) {
  return window['go']['main']['App']['UpdateDBUserRole'](arg1, arg2);
}
