// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDependencies() {
  return window['go']['main']['App']['CheckDependencies']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function InstallAndStartWithScoop() {
  return window['go']['main']['App']['InstallAndStartWithScoop']();
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
