// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckDependencies():Promise<main.DependencyStatus>;

export function CheckForUpdate():Promise<void>;

export function ClearLogs():Promise<void>;

export function DeactivateMultipleDBUsers(arg1:Array<string>):Promise<void>;

export function DeleteDBAnnouncement(arg1:string):Promise<void>;

export function DeleteDBKnowledgeDoc(arg1:string):Promise<void>;

export function DeleteDBUser(arg1:string):Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetDBAnnouncements():Promise<Array<main.DBAnnouncement>>;

export function GetDBKnowledgeDocs():Promise<Array<main.DBKnowledgeDoc>>;

export function GetDBUsers():Promise<Array<main.DBUser>>;

export function GetInactiveDBUsers():Promise<Array<main.DBUser>>;

export function GetLocalIP():Promise<string>;

export function GetLogs():Promise<Array<string>>;

export function GetStatus():Promise<main.ServerStatus>;

export function HardDeleteAllInactiveUsers():Promise<void>;

export function HardDeleteDBUser(arg1:string):Promise<void>;

export function InstallAndStartWithScoop():Promise<void>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function ReactivateDBUser(arg1:string):Promise<void>;

export function ResetDBUserPassword(arg1:string,arg2:string):Promise<void>;

export function StartServer():Promise<void>;

export function StopServer():Promise<void>;

export function UpdateDBUserPosition(arg1:string,arg2:string):Promise<void>;

export function UpdateDBUserRole(arg1:string,arg2:string):Promise<void>;
